

INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('admin');
INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('client');


INSERT into ADMIN.USERS (ROLE, EMAIL, PASSWORD, ISBLOCKED) VALUES (1, 'dartvader@mail.ru', 'dartvader', FALSE);


INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ("Exam");
INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ("SchoolCertificate");


INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Механико-математический факультет', 5, 10);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Физико-технический факультет', 2, 6);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Биологический факультет', 3, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Филологический факультет', 5, 8);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Географический факультет', 2, 7);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Факультет компьютерных наук', 1, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Экономический факультет', 2, 10);


INSERT INTO ADMIN.SUBJECT (name) VALUES ('Математика');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('История');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('География');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Химия');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Физика');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Английский');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Украинский');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Биология');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Информатика');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Экономика');
