

INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('admin');
INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('client');

INSERT into ADMIN.USERS (ROLE, EMAIL, PASSWORD, ISBLOCKED) VALUES (1, 'obivan@gmail.com', 'obivan', FALSE);

INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ('Exam');
INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ('SchoolCertificate');

INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Mechanics and Mathematics Faculty', 5, 10);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Physics and Technology Faculty', 2, 6);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Faculty of Biology', 3, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Faculty of Philology', 5, 8);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Faculty of Geography', 2, 7);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Faculty of Computer Science', 1, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Faculty of Economics', 2, 10);

INSERT INTO ADMIN.SUBJECT (name) VALUES ('Mathematics');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('History');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Geography');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Chemistry');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Physics');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('English');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Ukrainian');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Biology');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Computer science');
INSERT INTO ADMIN.SUBJECT (name) VALUES ('Economy');

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,5);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,5);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,1);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,8);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,4);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,6);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,2);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,3);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,5);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,9);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,10);
