connect 'jdbc:derby://localhost:1527/myDB;create=true;user=admin;password=admin';

DROP TABLE Submission_Subject;
DROP TABLE Faculty_Subject;
DROP TABLE Grade_Type;
DROP TABLE Subject;
DROP TABLE Submission;
DROP TABLE Faculty;
DROP TABLE Enrollee;
DROP TABLE Administrator;
DROP TABLE Users;
DROP TABLE Role;

CREATE TABLE Role(
  id integer NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  role_type varchar(10) NOT NULL UNIQUE
);

INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('admin');
INSERT into ADMIN.ROLE (ROLE_TYPE) VALUES ('client');

CREATE TABLE Users(
  id integer NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  role INT REFERENCES Role (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  email varchar(60) NOT NULL UNIQUE,
  password VARCHAR (50) NOT NULL,
  isBlocked BOOLEAN DEFAULT FALSE
);

INSERT into ADMIN.USERS (ROLE, EMAIL, PASSWORD, ISBLOCKED) VALUES (1, 'dartvader@mail.ru', 'dartvader', FALSE);

CREATE TABLE Administrator(
  id integer NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  user_id INTEGER REFERENCES Users (id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Enrollee(
  id integer NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  full_name varchar(70) NOT NULL,
  city varchar(30) NOT NULL,
  region varchar(30) NOT NULL,
  school_name varchar(50) NOT NULL,
  certificate BLOB,
  user_id INTEGER REFERENCES Users (id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Faculty(
  id INT NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  name varchar(50) NOT NULL UNIQUE,
  budgetVolume integer NOT NULL,
  totalVolume integer NOT NULL
);

INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Механико-математический факультет', 5, 10);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Физико-технический факультет', 2, 6);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Биологический факультет', 3, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Филологический факультет', 5, 8);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Географический факультет', 2, 7);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Факультет компьютерных наук', 1, 5);
INSERT INTO ADMIN.FACULTY (NAME, BUDGETVOLUME, TOTALVOLUME) VALUES('Экономический факультет', 2, 10);

CREATE TABLE Subject(
  id INT NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  name varchar(60) NOT NULL UNIQUE
);

INSERT INTO Subject (name) VALUES ('maths');
INSERT INTO Subject (name) VALUES ('history');
INSERT INTO Subject (name) VALUES ('geography');
INSERT INTO Subject (name) VALUES ('chemistry');
INSERT INTO Subject (name) VALUES ('physics');
INSERT INTO Subject (name) VALUES ('english');
INSERT INTO Subject (name) VALUES ('ukrainian');
INSERT INTO Subject (name) VALUES ('biology');
INSERT INTO Subject (name) VALUES ('computer_science');
INSERT INTO Subject (name) VALUES ('economics');

CREATE TABLE Faculty_Subject(
  id INT NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  faculty_id integer REFERENCES Faculty (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  subject_id integer REFERENCES Subject (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  UNIQUE (faculty_id, subject_id)
);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (1,5);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,5);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (2,1);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,8);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (3,4);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,6);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (4,2);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,3);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (5,5);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (6,9);

INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,7);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,1);
INSERT INTO ADMIN.FACULTY_SUBJECT (FACULTY_ID, SUBJECT_ID) VALUES (7,10);

CREATE TABLE Submission(
  id INT NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  faculty_id integer REFERENCES Faculty (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  enrollee_id integer REFERENCES Enrollee (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  UNIQUE (faculty_id, enrollee_id)
);

CREATE TABLE Grade_Type(
  id integer NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  grade_type VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ('Exam');
INSERT INTO ADMIN.GRADE_TYPE (GRADE_TYPE) VALUES ('SchoolCertificate');

CREATE TABLE Submission_Subject(
  id INT NOT NULL PRIMARY KEY generated always AS identity (START WITH 1, INCREMENT BY 1),
  submission_id integer REFERENCES Submission (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  subject_id integer REFERENCES Subject (id) ON DELETE CASCADE ON UPDATE RESTRICT,
  grade INT NOT NULL,
  grade_type INTEGER REFERENCES Grade_Type(id) ON DELETE CASCADE ON UPDATE RESTRICT,
  UNIQUE (subject_id, submission_id, grade_type)
);



disconnect;
exit;


