INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,7,178,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,5,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,1,188,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,3,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,4,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,5,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,6,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,7,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,8,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (1,10,4,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,7,178,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,5,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,1,188,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,3,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,4,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,5,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,6,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,7,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,8,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (2,10,4,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,7,178,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,9,150,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,1,188,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,3,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,4,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,5,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,6,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,7,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,8,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (3,10,4,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,2);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,7,124,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,5,199,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,3,178,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,3,2,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,6,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,7,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,9,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (4,10,3,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,2);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,7,124,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,8,165,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,4,156,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,3,2,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,6,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,7,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,9,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (5,10,3,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,3);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,7,189,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,10,185,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,1,199,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,4,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,5,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,7,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (6,10,8,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,3);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,7,189,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,5,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,1,199,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,4,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,5,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,7,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (7,10,8,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,3);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,7,189,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,5,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,1,199,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,4,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,5,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,7,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (8,10,8,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,4);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,7,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,9,165,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,1,138,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,3,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,4,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,5,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (9,10,8,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,4);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,7,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,10,140,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,1,138,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,3,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,4,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,5,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (10,10,8,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,5);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,7,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,8,159,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,4,160,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,1,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,2,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,3,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,4,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,6,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (11,10,2,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (4,5);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,7,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,6,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,2,159,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,1,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,2,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,3,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,4,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,6,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (12,10,2,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,5);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,7,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,3,200,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,5,200,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,1,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,2,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,3,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,4,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,6,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (13,10,2,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,6);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,7,150,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,1,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,9,139,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,1,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,3,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,4,2,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,6,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (14,10,3,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,6);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,7,150,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,1,143,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,10,167,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,1,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,3,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,4,2,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,6,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (15,10,3,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,7);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,7,149,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,8,166,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,4,171,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,5,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,6,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (16,10,12,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (4,7);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,7,149,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,6,166,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,2,159,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,5,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,6,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (17,10,12,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,7);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,7,149,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,3,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,5,181,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,5,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,6,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,7,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (18,10,12,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,8);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,7,191,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,1,188,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,5,198,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (19,10,12,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,8);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,7,191,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,1,188,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,5,198,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (20,10,12,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,8);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,7,191,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,1,188,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,9,178,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,4,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,5,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,8,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,9,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (21,10,12,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,9);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,7,134,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,1,125,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,10,150,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,1,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,8,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (22,10,9,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,9);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,7,134,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,3,156,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,5,176,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,1,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,8,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (23,10,9,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,10);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,7,150,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,8,157,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,4,161,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,5,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (24,10,7,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,10);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,7,150,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,1,168,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,5,163,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,5,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,6,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (25,10,7,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,11);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,7,188,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,1,200,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,5,200,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,1,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (26,10,7,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,11);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,7,188,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,1,200,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,5,200,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,1,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (27,10,7,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,12);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,7,167,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,8,178,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,4,180,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,8,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (28,10,4,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (4,12);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,7,167,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,6,159,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,2,192,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,8,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,9,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (29,10,4,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,13);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,7,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,3,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,5,195,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,3,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,7,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,8,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,9,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (30,10,12,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,13);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,7,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,1,172,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,9,174,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,3,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,6,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,7,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,8,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,9,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (31,10,12,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,14);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,7,138,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,1,149,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,10,154,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,7,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (32,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,14);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,7,138,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,1,149,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,5,160,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,1,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,2,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,5,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,7,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (33,10,10,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,15);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,7,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,1,170,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,5,179,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,5,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (34,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,15);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,7,176,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,8,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,4,167,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,5,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,9,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (35,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (4,16);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,7,124,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,6,139,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,2,140,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,1,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,4,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,5,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,8,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (36,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,16);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,7,124,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,3,147,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,5,137,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,1,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,2,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,4,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,5,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,8,3,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (37,10,10,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,17);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,7,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,1,170,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,9,161,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (38,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (7,17);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,7,180,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,1,170,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,10,188,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,2,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,4,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (39,10,10,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (1,18);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,7,156,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,1,170,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,5,162,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,2,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,4,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (40,10,2,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (2,18);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,7,156,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,1,170,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,5,162,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,2,5,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,3,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,4,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,7,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,8,4,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (41,10,2,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (3,19);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,7,199,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,8,191,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,4,197,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,4,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,6,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,7,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (42,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (4,19);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,7,199,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,6,187,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,2,191,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,1,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,4,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,6,12,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,7,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,8,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (43,10,10,2);




INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (5,20);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,7,134,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,3,187,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,5,155,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,4,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,7,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (44,10,10,2);


INSERT INTO ADMIN.SUBMISSION (FACULTY_ID, ENROLLEE_ID) VALUES (6,20);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,7,134,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,1,173,1);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,9,180,1);

INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,1,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,2,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,3,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,4,8,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,5,11,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,6,6,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,7,10,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,8,9,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,9,7,2);
INSERT INTO ADMIN.SUBMISSION_SUBJECT (SUBMISSION_ID, SUBJECT_ID, GRADE, GRADE_TYPE) VALUES (45,10,10,2);



